# Multi container pod

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  - name: busybox-container
    image: centos7
    command: ["sleep", "10000"]