apiVersion: v1
kind: Secret
metadata:
  name: ecomm-cm
data:
  DBUSERNAME: "YWRtaW4K"
  PASSWORD: "REIxMjM0Cg=="
  API_TOKEN: "YWJzaGdrZGZpZGZpc2xramcK"

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    envFrom:
      - secretRef:
          name: ecomm-secret-cm