apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

# Cluster IP svc
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc
# spec:
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

#Loadbalancer svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-alb-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
#NodePort SVC
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: MyApp
#   ports:
#     - port: 80
#       targetPort: 80
#       # will allocate a port from a range (default: 30000-32767)
#       nodePort: 30007   # port number which would be reaching the K8 node